// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwxiaiufgjmikhykllkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3eGlhaXVmZ2ptaWtoeWtsbGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjU3MTgsImV4cCI6MjA2NTg0MTcxOH0.wKGALdv6bKsMg1n4Q5vZ_RZ7zPnuk2pDEaFqSUXweVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});